name: "agricultural vision"
mode: "dev"
port: 8080
version: "v0.0.1"
start_time: "2025-01-14"
machine_id: 1

log:
  level: "debug"
  filename: "./log/agricultural_vision.log"
  max_size: 1000
  max_age: 3600
  max_backups: 5

mysql:
  host: "101.200.122.3"
  port: 3306
  user: "agricultural_vision"
  password: "BpdRG8KFY7FFTP28"
  db: "agricultural_vision"
  max_open_conns: 100
  max_idle_conns: 20

redis:
  host: "127.0.0.1"
  password: ""
  port: 6379
  db: 0
  pool_size: 100
  min_idle_conns: 50

ai:
  system_content: "你是一个农业小助手，回答时使用纯文本，不是用markdown语法，语言尽量简练"
  api_key: "sk-0a03ab3a2d18455e97d0a40f4fc20671"
  api_url: "https://api.deepseek.com/v1/chat/completions"